version: "3"
services:

  # 作業用コンテナ
  # 全てのソースはこのコンテナ内で編集を行う
  work:
    image: ghcr.io/kengo-k/account-work:202304012341-a0b0acf
    container_name: account_work
    tty: true
    volumes:
      - ./:/workspace
      - ./common:/workspace/frontend/src/common
      - ./common:/workspace/backend/src/main/common
      - $HOME/.ssh:/home/container-user/.ssh
      - $PWD/account-work/config:/home/container-user/.ssh/config
    networks:
      - account_net
    depends_on:
      - frontend
      - backend

  frontend:
    image: ghcr.io/kengo-k/dev-base-nodejs:202304012334-aa29e8c
    container_name: account_frontend
    ports:
      - 80:80
    tty: true
    volumes:
      - ./frontend/:/workspace
      - ./common/:/workspace/src/common
      - $HOME/.ssh:/home/container-user/.ssh
    networks:
      - account_net

  backend:
    image: ghcr.io/kengo-k/dev-base-nodejs:202304012334-aa29e8c
    container_name: account_backend3
    tty: true
    volumes:
      - ./backend/:/workspace
      - ./common/:/workspace/src/main/common
      - $HOME/.ssh:/home/container-user/.ssh
    ports:
      - 8080:8080
    networks:
      - account_net

  # db:
  #   image: postgres:12.6
  #   env_file:
  #     - db.env
  #   container_name: account_db
  #   volumes:
  #     - "$PWD/data:/var/lib/postgresql/data"
  #   networks:
  #     - account_net

networks:
  account_net:
