version: "3"
services:

  # 作業用コンテナ
  # 全てのソースはこのコンテナ内で編集を行う
  work:
    image: ghcr.io/kengo-k/dev-base-ubuntu:202305222318-61621c2
    container_name: account_work
    hostname: work
    tty: true
    volumes:
      - ./:/workspace
      - ./common:/workspace/frontend/src/common
      - ./common:/workspace/backend/src/main/common
      - $HOME/.ssh:/home/container-user/.ssh
      - $PWD/docker/account-work/config:/home/container-user/.ssh/config
    networks:
      - account_net
    depends_on:
      - frontend
      - backend

  frontend:
    image: ghcr.io/kengo-k/dev-base-nodejs:202305222323-c664e22
    container_name: account_frontend
    hostname: frontend
    ports:
      - 80:80
    tty: true
    volumes:
      - ./frontend/:/workspace
      - ./common/:/workspace/src/common
      - $HOME/.ssh:/home/container-user/.ssh
    depends_on:
      - backend
    networks:
      - account_net

  backend:
    image: ghcr.io/kengo-k/account-backend:202305222327-a529947
    container_name: account_backend
    hostname: backend
    tty: true
    volumes:
      - ./backend/:/workspace
      - ./common/:/workspace/src/main/common
      - ./database.yml:/workspace/src/main/core/database.yml
      - ./database.yml:/workspace/migration/database.yml
      - $HOME/.ssh:/home/container-user/.ssh
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - account_net

  db:
    image: postgres:12.6
    env_file:
      - db.env
    container_name: account_db
    volumes:
      - "$PWD/data:/var/lib/postgresql/data"
    networks:
      - account_net

networks:
  account_net:
